# A50 container mount hooks.  Sourced by /var/lib/lxc/android/mount.sh, which
# LXC runs in the container's own mount namespace before Android's init starts.
#
# Everything here overrides a file the Halium GSI or Samsung's vendor image
# ships.  The host cannot do it: /vendor and /system are mounted separately in
# the container's namespace, so a bind mount made on the host is invisible in
# there.  That is why these are hooks and not overlay files.
#
# The sources are generated by /usr/local/bin/a50-container-prepare.sh, which
# runs before lxc-android-config.service.  Each bind is guarded, so a missing
# source degrades to "unfixed" rather than to a container that will not start.

A50_HOOKS=/var/lib/lxc/android

# Samsung's watchdogd opens /dev/watchdog (misc minor 130); that open spins
# forever in kernel while holding the global misc_mtx, which freezes EVERY
# misc-device open system-wide - mali0, ion, binder, hwbinder, uinput.  Proof:
# "MISCDBG: pid=N comm=watchdogd GOTLOCK minor=130" with no matching release.
# docs/experiments/006-what-we-missed.md
if [ -f "$A50_HOOKS/init.exynos9610.rc.nowatchdog" ]; then
    mount --bind "$A50_HOOKS/init.exynos9610.rc.nowatchdog" \
        "${LXC_ROOTFS_MOUNT}/vendor/etc/init/init.exynos9610.rc"
fi

# f_conn_gadget.c calls misc_register() on a STATIC miscdevice with no
# already-registered guard.  usb_moded (host) and vendor_init (container) both
# drive USB gadget configfs, so the function is instantiated twice;
# INIT_LIST_HEAD then points that node at itself while its old neighbours still
# point to it, making misc_list circular - and the next list_for_each_entry in
# misc_open() spins forever holding misc_mtx.  Ubuntu Touch's usb_moded owns
# USB here, so the Android side simply must not create the gadget.
# docs/experiments/006-what-we-missed.md
if [ -f "$A50_HOOKS/usb.rc.empty" ]; then
    mount --bind "$A50_HOOKS/usb.rc.empty" \
        "${LXC_ROOTFS_MOUNT}/vendor/etc/init/init.exynos9610.usb.rc"
fi

# Two Samsung vendor daemons wedge the container: emservice spins inside a
# vendor module holding misc_mtx, and cass blocks forever opening umts_boot0
# before the CP has booted.  Neither has any role in Ubuntu Touch.
if [ -f "$A50_HOOKS/rc.empty" ]; then
    mount --bind "$A50_HOOKS/rc.empty" \
        "${LXC_ROOTFS_MOUNT}/vendor/etc/init/emservice.rc"
    mount --bind "$A50_HOOKS/rc.empty" \
        "${LXC_ROOTFS_MOUNT}/vendor/etc/init/cass.rc"
fi

# The Halium GSI's init.disabled.rc points BOTH vendor.audio-hal and
# vendor.audio-hal-2-0 at binaries that do not exist (_DISABLED /
# _HYBRIS_DISABLED suffixes), so no Android audio HAL runs at all.
# docs/experiments/007-abox-firmware-too-early.md
if [ -f "$A50_HOOKS/init.disabled.rc.audiofix" ]; then
    mount --bind "$A50_HOOKS/init.disabled.rc.audiofix" \
        "${LXC_ROOTFS_MOUNT}/system/etc/init/init.disabled.rc"
fi

# The real Samsung HAL (audio.primary.exynos9610.so) is 32-bit only and exists
# only in /vendor/lib/hw, so a 64-bit audio stack cannot load it and silently
# falls back to the generic stub - which hands back a stream with a NULL op
# table and discards every write.  Android's own 64-bit audio.hidl_compat
# wrapper forwards the legacy calls to the real 32-bit HIDL service over
# /dev/hwbinder; present it at the name a 64-bit loader resolves.
if [ -f /android/system/lib64/hw/audio.hidl_compat.default.so ]; then
    mount --bind /android/system/lib64/hw/audio.hidl_compat.default.so \
        "${LXC_ROOTFS_MOUNT}/vendor/lib64/hw/audio.primary.default.so"
fi

# The stock mixer_paths.xml routes the speaker amplifier from SIFS1, which is
# fed by RDMA7 - a channel this ABOX DSP firmware NACKs - so nothing ever
# reaches the amp.  The generated copy points UAIF2 at SIFS0 and drops the
# codec from the speaker-only paths.
# docs/experiments/007-abox-firmware-too-early.md
if [ -f "$A50_HOOKS/mixer_paths.a50.xml" ]; then
    mount --bind "$A50_HOOKS/mixer_paths.a50.xml" \
        "${LXC_ROOTFS_MOUNT}/vendor/etc/mixer_paths.xml"
fi
